[package]
name = "impressions"
version = "0.0.0"
description = "An experimental binary analysis utility inspired by the City Building series from Impressions Games"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
repository = "https://github.com/dbalcomb/impressions"
license = "MIT OR Apache-2.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
